package MonopolyGameWeb.logic.events;

public enum EventType
{
    GAME_START, GAME_OVER, GAME_WINNER, PLAYER_RESIGNED,
    PLAYER_LOST, DICE_ROLL, MOVE, PASSED_START_SQUARE, LANDED_ON_START_SQUARE, GO_TO_JAIL,
    PROMPT_PLAYER_TO_BUY_ASSET, PROMPT_PLAYER_TO_BUY_HOUSE, ASSET_BOUGHT_MESSAGE, HOUSE_BOUGHT_MESSAGE,
    SURPRISE_CARD, WARRANT_CARD, GET_OUT_OF_JAIL_CARD, PAYMENT, PLAYER_USED_OUT_OF_JAIL_CARD
}
